# Production
version: '3.2'
services:
  briefcast:
    networks:
      - default
      - internal
  briefcast_core:
    networks:
      - internal
networks:
  default:
    external:
      name: myservices_default
  internal: