version: '3.2'
services:
  briefcast:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "8088:8088"
    environment:
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      PUBLIC_FIREBASE_API_KEY: ${PUBLIC_FIREBASE_API_KEY}
      PUBLIC_FIREBASE_AUTH_DOMAIN: ${PUBLIC_FIREBASE_AUTH_DOMAIN}
      PUBLIC_FIREBASE_PROJECT_ID: ${PUBLIC_FIREBASE_PROJECT_ID}
      PUBLIC_FIREBASE_STORAGE_BUCKET: ${PUBLIC_FIREBASE_STORAGE_BUCKET}
      PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      PUBLIC_FIREBASE_APP_ID: ${PUBLIC_FIREBASE_APP_ID}
      PUBLIC_FIREBASE_MEASUREMENT_ID: ${PUBLIC_FIREBASE_MEASUREMENT_ID}
    volumes:
      - ./app:/app
      - ${NPM_CACHE}:/app/.npm
  briefcast_core:
    build:
      context: ./core
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/key.json:ro
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      PUBLIC_FIREBASE_API_KEY: ${PUBLIC_FIREBASE_API_KEY}
      PUBLIC_FIREBASE_AUTH_DOMAIN: ${PUBLIC_FIREBASE_AUTH_DOMAIN}
      PUBLIC_FIREBASE_PROJECT_ID: ${PUBLIC_FIREBASE_PROJECT_ID}
      PUBLIC_FIREBASE_STORAGE_BUCKET: ${PUBLIC_FIREBASE_STORAGE_BUCKET}
      PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      PUBLIC_FIREBASE_APP_ID: ${PUBLIC_FIREBASE_APP_ID}
      PUBLIC_FIREBASE_MEASUREMENT_ID: ${PUBLIC_FIREBASE_MEASUREMENT_ID}
      FIREBASE_ADMIN_EMAIL: ${FIREBASE_ADMIN_EMAIL}
      FIREBASE_ADMIN_PASSWD: ${FIREBASE_ADMIN_PASSWD}
