# Production
version: '3.2'
services:
  briefcast:
    networks:
      - default
      - internal
  briefcast_core:
    networks:
      - internal
networks:
  default:
    name: myservices_default
    external: true      
  internal: