version: '3.2'
services:
  briefcast_web:
    container_name: briefcast_web
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - "9696:9696"
    volumes:
      - ./:/app
